### ISSUE TITLE
Accepted Formats?

### ISSUE THREAD

**Issue by martinmts** [TechWilk/bible-verse-parser#18]
Hi,
Thanks for sharing it.
I had a few tests and found out that it cannot handle some common reference formats, for instance,

Gen 4:26-5:1
Gen 1:1; 4:26

Also, the sample code is interesting. I'm not quite understanding.
>1 John 5:4-17, 19-21 & Samuel 2

There is no book called "Samuel". It has to be either "1 Samuel" or "2 Samuel".

I hope it can handle something as complex as this:
>Gen 1:1, 3-4; 4:26-5:1; Lev 4:5; 5:2; Phlm 1-2; 1 John 1;2 John 2; 3 John; Pss 1-2

Thanks!

**Comment by TechWilk** [comment]
Thanks for opening the issue with these!

You are quite right about "Samuel" not existing and quite clearly an error on my part. I'll get that fixed.
I wrote the readme rather rapidly and think I originally had 1 John and 1 Samuel in the example, then decided to swap 1 Samuel out for a book without the numerical prefix for variety. I removed the number but omitted to change the book name itself!

It's really helpful that you've included thorough examples of things which aren't working for you. I am aware there could be some issues of ranges which cross chapter boundaries, such as `Gen 4:26-5:1`, as it's not something I have previously tested.
 I'll take a look & see if I can get them working.

**Comment by TechWilk** [comment]
So I think this issue is split into three sections:
- [ ] Fix the examples in the readme (`Samuel` does not exist!)
- [ ] Support semicolon `;` as a passage separator (e.g. `Gen 1:1; 4:26`)
- [ ] Support passages which span across chapter boundries (e.g. `Gen 4:26-5:1`)

I'll update this list as they get sorted

**Comment by TechWilk** [comment]
I've released version 2.0.0 which supports passages which span across chapter boundaries. 
Let me know if you have any issues with this!
