### ISSUE TITLE
Be able to parse verses in languages other than English

### ISSUE THREAD

**Issue by lucaromanoxyz** [TechWilk/bible-verse-parser#74]
When initializing the instance, the data structure is provided to be able to parse verses in languages other than English.

**Comment by TechWilk** [comment]
Thank you for raising this and providing a Pull Request!
This seems like a valuable change.

As it stands, I haven't tested the parser with non-ascii verse references, so do let me know if you run into any problems with it.

**Comment by TechWilk** [comment]
I've merged your changes and added a few more so you can also configure the $separators (if necessary).
Do let me know if there's anything else you feel would improve the package.

Thanks again for your work on this
